dist: trusty
sudo: false
language: node_js
node_js:
  - "12"
addons:
  chrome: stable
cache:
  directories:
    - ./node_modules
branches:
  only:
    - master
install:
  - npm i -g firebase-tools @angular/cli
  - npm i && ng build --prod
script:
  - npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox
after_success:
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then firebase deploy --token $FIREBASE_TOKEN; fi'