language: node_js
node_js:
  - "12"
branches:
  only:
    - master
install:
  - npm i -g firebase-tools @angular/cli
  - npm i && ng build --prod
after_success:
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then firebase deploy --token $FIREBASE_TOKEN; fi'